name: Playwright Tests
on: push

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    env:
      PGHOST: localhost
      PGDATABASE: next_js_example_spring_2022
      PGUSERNAME: next_js_example_spring_2022
      PGPASSWORD: next_js_example_spring_2022

    steps:
      - name: Start preinstalled PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create database user
        run: |
          sudo -u postgres psql --command="CREATE USER next_js_example_spring_2022 PASSWORD 'next_js_example_spring_2022'" --command="\du"
      - name: Create database and allow user
        run: |
          sudo -u postgres createdb --owner=next_js_example_spring_2022 next_js_example_spring_2022
      - uses: actions/checkout@v2
        # Use the official setup-node action (sets up Node.js):
      # https://github.com/actions/setup-node
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - uses: microsoft/playwright-github-action@v1

      # - name: Install dependencies
      #   run: yarn
      # - name: Run migrations
      #   run: yarn migrate up
      # - name: Run tests
      #   run: yarn playwright test

      # - name: Install dependencies
      #   run: yarn
      # - name: Install playwright
      #   run: yarn playwright install-deps
      # - run: yarn migrate up
      # - name: Build localhost
      #   run: yarn build & yarn playwright test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
